apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microblog-command
  template:
    metadata:
      labels:
        app: microblog-command
    spec:
      containers:
      - name: command-service
        image: sebarray/microblog-command-service   
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/microblog"
---
apiVersion: v1
kind: Service
metadata:
  name: microblog-command
spec:
  type: LoadBalancer  
  ports:
  - port: 8092
    targetPort: 8081
  selector:
    app: microblog-command
