apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microblog-query
  template:
    metadata:
      labels:
        app: microblog-query
    spec:
      containers:
      - name: query-service
        image: microblog-query-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/microblog"
---
apiVersion: v1
kind: Service
metadata:
  name: microblog-query
spec:
  type: LoadBalancer  
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: microblog-query
